all: thread_counter pthread_example
thread_counter: thread_counter.c
	gcc -std=c99 -o thread_counter thread_counter.c -lpthread

pthread_example: pthread_example.c
	gcc -std=c99 -o pthread_example pthread_example.c -lpthread

